<div class="panel-heading">
	<?php echo $this->__('Product Salon')?>
</div>
<div >
	<a href="<?php echo $this->helper('salon')->getUrl('admin/product')?>" class="btn btn-default">
		<?php echo Mage::helper('salon')->__('Product List')?>
	</a>
	<a style="margin-left: 9px;" href="<?php echo $this->helper('salon')->getUrl('admin/product/new')?>" class="btn btn-default">
		<?php echo Mage::helper('salon')->__('Add New')?>
	</a>
</div>
<br/>