<?php $salon = $this->getCurrentSalon()?>
<div id="dealer_locator">
	<div id="map_canvas" style="height: 570px"></div>
</div>
<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
<script type="text/javascript">
    //<![CDATA[
    var lat = '<?php echo $salon->getLat() ?>';
    var lng = '<?php echo $salon->getLng() ?>';
    var bounds;
    var infowindow;
    var map = new google.maps.Map(document.getElementById('map_canvas'), {
		zoom: 10,
	    center: new google.maps.LatLng(lat, lng)
	});
	var infowindow = new google.maps.InfoWindow({maxWidth: 320});
	var marker, i;
	var bounds = new google.maps.LatLngBounds();
	var marker = new google.maps.Marker({
	    position: new google.maps.LatLng(lat, lng),
	    map: map,
	    info:  '<div id="content">'+
 	   '<div id="siteNotice">'+
        '</div>'+
        '<h2 id="firstHeading" class="firstHeading">'+'<?php echo  $salon->getSalonName()?>'+'</h2>'+
        '<div id="bodyContent">'+
        '<p>' + '<?php echo $salon->getAddress()?>'
          + '<?php echo $salon->getCity() ? ', '. $salon->getCity() : ''?>' + '<?php echo $salon->getRegionId() ? ', '.$salon->getRegionId() : ''?>' + '<?php echo $salon->getRegion() ? ', '.$salon->getRegion() : ''?>' + '</p>'+
			'<p><a href="'+location.protocol + '//' + location.host + '/<?php echo $salon->getSalonUrl()?>/' + 'reservation">Reservation</a></p>'+ 
         '</div>'+
        '</div>'
		});
	infowindow.setContent(marker.info);
	infowindow.open(map, marker);
	google.maps.event.addListener(marker, 'click', (function(marker, i) {
		return function() {
	    	infowindow.setContent(marker.info);
	        infowindow.open(map, marker);
		}
	})(marker, i));
    //]]>
</script>