<?php 	
//Mage::getSingleton('checkout/session')->unsSalonReservation();
$helper = $this->helper('salon');
$_serviceCollection = $this->getServiceCollection();
?>
<?php if(!$_serviceCollection):?>
<h3>Our salon is not working at this day!</h3>
<?php else:?>
<div class="table" id="my-custom-table">
	<?php foreach ($_serviceCollection as $service):?>
		<?php $dateTime = $this->getDateTime();?>
		<div>
			<h3><?php echo $service->getServiceName() ?> (<?php echo $service->getDuration() . $this->__('&nbsp;minutes') ?>)</h3>
		</div>
		<?php $timeFrame = $this->getTimeFrame($service->getDuration(), $this->getWorkingTime())?>
		<div class="time-frame">
			<ul class="list-unstyled">
				<?php $haftTimeFrame = ceil($timeFrame / 2)?>
				<?php for($i = 1; $i <= $timeFrame; $i++):?>
					<?php 
						$timetpm = $dateTime->format('H:i');
						$nextDate = new DateTime($timetpm);
						$nextDate->modify( '+ '.$service->getDuration().' minutes');
						$timeroot = $dateTime->format('H:i');
						$timeFrameString = $dateTime->format('H:i').' - '. $nextDate->format('H:i');
					?>
						<li style="position: relative" onclick="processBooking(this, event)" class="<?php echo $this->getCssClassBooked($service->getEntityId(), $timeFrameString)?>" id="<?php echo $this->getElementId($service, $i)?>" title="<?php echo $timeFrameString ?>">
							<span class="time-duration"><?php echo $timeFrameString?></span>
							<input type="hidden" id="<?php echo $this->getElementId($service, $i)?>-service-name" value="<?php echo $service->getServiceName()?>">
							<input type="hidden" id="<?php echo $this->getElementId($service, $i)?>-service-price" value="<?php echo $service->getSpecialPrice() ? $service->getSpecialPrice() : $service->getPrice()?>">
							<input type="hidden" id="<?php echo $this->getElementId($service, $i)?>-service-id" value="<?php echo $service->getEntityId()?>">
						</li>
					<?php $dateTime->modify( '+ '.$service->getDuration().' minutes' ) ?>
					<?php if (trim(substr($timeFrameString, strpos($timeFrameString, '-')+1)) == $this->getTimeEnd()) {
						break;
					}?>
				<?php endfor;?>
			</ul>
		</div>
		<div style="clear: both"></div>
		<?php unset($dateTime)?>
	<?php endforeach;?>
	<div style="clear: both"></div>
</div>	
<?php endif;?>
<script type="text/javascript">
//<![CDATA[
     var urlAddToCart = '<?php echo Mage::helper('salon')->getUrl('reservation/addToCart')?>';
     var miniLoading = '<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN).'frontend/salon/'.'default/'.'images/'.'mini_loading.gif' ?>';
	function processBooking(arg, event)
	{
		var params = {
				power: $(arg),
				serviceId: $('#search_service').val(),
				dateSelected: $('#pick-a-date').children('input').val(),
				messageEmptyCart: $('#checkout-wrapper').children('p'),
				checkoutWrap: $('#selected-item-wrapper'),
				totalPriceWrap: $('#total-price-services'),
				timeframe: $(arg).children('span').html(),
				getAttrByEle: function(Ele, attr)
				{
					return $(Ele).attr(attr);
				},
				price: $(arg).children('input:nth-child(3)').attr('value'),
				getServiceId:function(text)
				{
					var text = text.split("-");
					return text[1];
				},
		};
		if(params.power.hasClass('booked'))
		{
			return false;
		}
		if(params.power.hasClass('selected'))
		{
			
			//remove item on check out
			var selectedElementId = params.getAttrByEle(params.power, 'id') + '-selected-item';
			totalPrice = totalPrice - parseFloat(params.price);
			refreshCheckout(params.messageEmptyCart, params);
		}
		else
		{
			
			
			var idService = params.getAttrByEle(params.power, 'id')+'-selected-item';

			var cartElement = $(document.createElement('div')).addClass('selected-item').attr('id',idService);

			var serviceName = $(document.createElement('div')).html(params.getAttrByEle(params.power.children('input:nth-child(2)'), 'value'));

			var serviceDate = $(document.createElement('div')).html(params.dateSelected);
			
			var serviceTime = $(document.createElement('div')).html(params.power.children('span:nth-child(1)').html());
			
			var servicePrice = $(document.createElement('div')).html('Price:&nbsp$<span>'+params.getAttrByEle(params.power.children('input:nth-child(3)'), 'value')+'</span>.00');

			var serviceClose = $(document.createElement('span')).addClass('close-icon close').html('<span aria-hidden="true">&times;</span><span class="sr-only">Close</span>');

			cartElement.append(serviceName, serviceDate, serviceTime, servicePrice, serviceClose);
			totalPrice = totalPrice + parseFloat(params.price);
			ajaxAddToCart(params, cartElement, 'add');

			
		}
		$(serviceClose).click(function(){

			params.power = $(this).parent(),
			params.dateSelected = $(this).parent().children('div:nth-child(2)').html(),
			params.timeframe = $(this).parent().children('div:nth-child(3)').html(),
			params.price = $(this).parent().children('div:nth-child(4)').children('span').html(),
			
			totalPrice = totalPrice - parseFloat(params.price);
			
			refreshCheckout(params.messageEmptyCart, params);
		});
		
	}
	function refreshCheckout(stringEmpty, params)
	{
		//ajax remove item in cart
		ajaxAddToCart(params,'', 'remove');
		
		
	}
	function ajaxAddToCart(params, cartElement, type)
	{
		if(params.power.is('div'))
		{
			params.power.children('span').html('<img src="'+miniLoading+'"/>');
		}
		else
		{
			params.power.append('<img style="position: absolute; top:25%; left:37%;" src="'+miniLoading+'"/>');
		}
		jQuery.ajax({
    		type: "POST",
    		url: urlAddToCart,
    		data: {id: params.getServiceId(params.power.attr('id')), date: params.dateSelected, timeframe: params.timeframe, price: params.price, type: type, elementId: params.power.attr('id')+'-selected-item', serviceName: params.power.children('input:nth-child(2)').attr('value')},
    		dataType: "json",
    	    success: function(data){
    	    	params.power.children('img').remove();
    	    	params.totalPriceWrap.html('<strong>Total Price:</strong> $' + totalPrice + '.00');
        	    if(data.status === 'ERROR')
        	    {
            		alert(data.message);    
            	}
				if(type === 'add')
				{
					params.power.addClass('selected');
					params.checkoutWrap.append(cartElement);
					params.messageEmptyCart.hide();
					$('#submit-checkout-wrapper').show();
					$('#total-price-services').show();
				}
				else
				{
					if(params.power.is('div'))
					{
						liTarget = params.power.attr('id').replace('-selected-item','');
						$('#'+liTarget).removeClass('selected');
						params.power.remove();
					}
					else
					{
						params.power.removeClass('selected');
						var deleteTar = params.power.attr('id')+'-selected-item';
						$('#'+deleteTar).remove();
					}
					if(0 == $('#selected-item-wrapper').children('div').length)
					{
						$('#checkout-wrapper').children('p').show();
						$('#submit-checkout-wrapper').hide();
						$('#total-price-services').hide();
					} 
				}
			},
		}); 
	}
	//save reservation have selected when load page
	(function(){
		var reservationList = $('#selected-item-wrapper').children();
		var i=0;
		var dateValue = $('#pick-a-date').data('date');
		for( i=0; i < reservationList.length; i++)
		{
			
			var reservationDate = $(reservationList[i]).children('div:nth-child(2)').html();
			if($(reservationList[i]).is('div'))
			{
				if(reservationDate == dateValue)
				{
					var liTarget = $(reservationList[i]).attr('id').replace('-selected-item', '');
					$('#'+liTarget).addClass('selected');
				}
			}
		}
	})();
//]]>
</script>
