<?php
/**
 * Customer login form template
 *
 * @see app/design/frontend/base/default/template/customer/form/login.phtml
 */
/** @var $this Mage_Customer_Block_Form_Login */
?>
<div class="account-login col-md-4 col-md-offset-2">
	<div class="nk-form-wrapper">
		<div class="page-title">
	        <h1 class=""><?php echo $this->__('Log in to your account') ?></h1>
	    </div>
	    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
	    <form role="form" class="" action="<?php echo $this->getPostActionUrl() ?>" method="post" id="login-form">
	        <?php echo $this->getBlockHtml('formkey'); ?>
	        <div class="form-group">
				<label for="email" class="required control-label"><em>*</em><?php echo $this->__('Email Address') ?></label>
				<input type="text" name="login[username]" value="<?php echo $this->escapeHtml($this->getUsername()) ?>" id="email" class="form-control required-entry validate-email" title="<?php echo $this->__('Email Address') ?>" />
	        </div>
	        <div class="form-group">
	        	<label for="pass" class="required control-label"><em>*</em><?php echo $this->__('Password') ?></label>
				<input type="password" name="login[password]" class="form-control required-entry validate-password" id="pass" title="<?php echo $this->__('Password') ?>" />
	        </div>
			
	        <?php echo $this->getChildHtml('form.additional.info'); ?>
			<?php echo $this->getChildHtml('persistent.remember.me'); ?>
			<?php echo $this->getChildHtml('persistent.remember.me.tooltip'); ?>
	        <div class="form-group">
	        	<p class="">
	        		<button type="submit" class="btn nk-btn-default" title="<?php echo $this->__('Login') ?>" name="send" id="send2"><?php echo $this->__('Login') ?></button>
	            </p>
	            <p>
	            	<button style="padding-left: 0" type="button" title="<?php echo $this->__('Create an Account') ?>" class="btn btn-link" onclick="window.location='<?php echo Mage::helper('persistent')->getCreateAccountUrl($this->getCreateAccountUrl()) ?>';"><?php echo $this->__('Create an Account') ?></button>
		            <button type="button" class="btn btn-link" onclick="window.location='<?php echo $this->getForgotPasswordUrl() ?>';"><?php echo $this->__('Forgot Your Password?') ?></button>
	            </p>
	        </div>
	        <?php if (Mage::helper('checkout')->isContextCheckout()): ?>
	            <input name="context" type="hidden" value="checkout" />
	        <?php endif; ?>
	    </form>
	    <script type="text/javascript">
	    //<![CDATA[
	        var dataForm = new VarienForm('login-form', true);
	    //]]>
	    </script>
	</div>
</div>
