<div class="login-panel panel panel-default">
	<?php 	$sessionMessageArr = Mage::helper('salon')->getSessionMessage();?>
	<?php if (isset($sessionMessageArr['message']) && $sessionMessageArr['message']):?>
		<div id="message-session" class="<?php echo ($sessionMessageArr['type'] == 'error') ? 'text-danger' : 'text-success'?>">
			<blockquote class="<?php echo ($sessionMessageArr['type'] == 'error') ? 'bg-danger' : 'bg-success'?>">
				<?php echo $sessionMessageArr['message']?>
			</blockquote>
		</div>
	<?php endif;?>
	<div class="panel-heading">
		<h3 class="panel-title"><?php echo $this->__('Salon Admin Login')?></h3>
	</div>
	<div class="panel-body">
		<form method="post" role="form" id="salon-admin-login-form" action="<?php echo $this->getPostActionUrl() ?>">
			<fieldset>
				<div class="form-group">
					<input class="form-control" placeholder="E-mail" name="login[username]" type="email" autofocus>
				</div>
				<div class="form-group">
					<input class="form-control" placeholder="Password" name="login[password]" type="password" value="">
				</div>
				<div class="checkbox">
					<label>
						<input name="remember" type="checkbox" value="Remember Me">Remember Me
					</label>
				</div>
				<button type="submit" class="btn btn-custom-primary btn-lg btn-success btn-login">
					<i class="fa fa-arrow-circle-o-right"></i> <?php echo $this->__('Login')?>
				</button>
			</fieldset>
		</form>
	</div>
</div>
<script>
$(document).ready(function() {
    $('#salon-admin-login-form').bootstrapValidator({
        // To use feedback icons, ensure that you use Bootstrap v3.1.0 or later
        feedbackIcons: {
            valid: 'glyphicon glyphicon-ok',
            invalid: 'glyphicon glyphicon-remove',
            validating: 'glyphicon glyphicon-refresh'
        },
        fields: {
        	'login[username]': {
                validators: {
                    notEmpty: {
                        message: '<?php echo $this->__('Email is required') ?>'
                    },
                    emailAddress: {
                        message: '<?php echo $this->__('Email is not a valid. Ex: youname@yourdomain.com') ?>'
                    }
                }
            },
            'login[password]': {
                validators: {
                    notEmpty: {
                        message: '<?php echo $this->__('Password is required') ?>'
                    }
                }
            }
        }
    });
});
</script>