<div class="row content">
	<div class="col-sm-8">
		<?php echo $this->getChildHtml('salon.banner')?>
	</div>
	<div class="col-sm-4 nopadding">
		<?php echo $this->getChildHtml('salon.availability')?>
	</div>
</div>
<h3 >Our  Service</h3>
<div class="row content">
	<div class="col-sm-12">
		<?php echo $this->getChildHtml('salon.service.list')?>
	</div>
</div>
<h3 >Our  Product</h3>
<div class="row content">
	<div class="col-sm-12">
		<?php echo $this->getChildHtml('salon.product')?>
	</div>
</div>