<?php echo $this->getMessagesBlock()->getGroupedHtml()?>
<?php $collection = $this->getReservationCollection();?>
<div class="panel-heading"><?php echo $this->__('Reservation Management') ?></div>
<div class="page-title">
	<a style="margin: 0px 0px 10px 0px" class="btn btn-default" href="<?php echo Mage::helper('salon')->getUrl('admin/reservation/new')?>"><?php echo $this->__('Reservation New')?></a>
</div>

<table class="data-table table table-bordered" id="my-custom-table">
	<!-- <col width="1" />
	<col width="1" />
	<col />
	<col width="1" />
	<col width="1" />
	<col width="1" /> -->
	<thead>
		<tr>
			<th>
				<?php echo $this->__('Order Id') ?>
				<a href="javascript:void(0)" id="order_id" class="sort<?php echo $this->sort === 'order_id' ? ' '. strtolower($this->direct): null; ?>" style="text-decoration:none">&nbsp;<i class="fa fa-sort"></i></a>
			</th>
			<th>
				<?php echo $this->__('Customer Name') ?>
				<a href="javascript:void(0)" id="customer_name" class="sort<?php echo $this->sort === 'customer_name' ? ' '. strtolower($this->direct): null; ?>" style="text-decoration:none">&nbsp;<i class="fa fa-sort"></i></a>
			</th>
			<th>
				<?php echo $this->__('Service Name') ?>
				<a href="javascript:void(0)" id="service_name" class="sort<?php echo $this->sort === 'service_name' ? ' '. strtolower($this->direct): null; ?>" style="text-decoration:none">&nbsp;<i class="fa fa-sort"></i></a>
			</th>
			<th>
				<?php echo $this->__('Date Booking') ?>
				<a href="javascript:void(0)" id="time_stamp" class="sort<?php echo $this->sort === 'time_stamp' ? ' '. strtolower($this->direct): null; ?>" style="text-decoration:none">&nbsp;<i class="fa fa-sort"></i></a>
			</th>
			<th>
				<?php echo $this->__('Staff') ?>
				<a href="javascript:void(0)" id="staff_id" class="sort<?php echo $this->sort === 'staff_id' ? ' '. strtolower($this->direct): null; ?>" style="text-decoration:none">&nbsp;<i class="fa fa-sort"></i></a>
			</th>
			<th><?php echo $this->__('Time Frame') ?></th>
			<th>
				<?php echo $this->__('Status') ?>
				<a href="javascript:void(0)" id="status" class="sort<?php echo $this->sort === 'status' ? ' '. strtolower($this->direct): null; ?>" style="text-decoration:none">&nbsp;<i class="fa fa-sort"></i></a>
			</th>
			<th>
				<?php echo $this->__('Subtotal') ?>
				<a href="javascript:void(0)" id="subtotal" class="sort<?php echo $this->sort === 'subtotal' ? ' '. strtolower($this->direct): null; ?>" style="text-decoration:none">&nbsp;<i class="fa fa-sort"></i></a>
			</th>
			<th><span class="nobr"><?php echo $this->__('Confirm') ?></span></th>
			<th><span class="nobr"><?php echo $this->__('Delete') ?></span></th>
		</tr>
	</thead>
	<tbody class="table-content">
        <?php $_odd = ''; ?>
        <?php foreach ($collection as $reservation): ?>
        <tr title ="<?php echo isset($reservation['entity_id']) ? $reservation['entity_id'] : ''?>">
			<td><span class="nobr"><?php echo isset($reservation['order_id']) ? $reservation['order_id'] : ''?></span></td>
			<td><span class="nobr"><?php echo isset($reservation['customer_name']) ? $reservation['customer_name'] : '' ?></span></td>
			<td><span class="nobr"><?php echo isset($reservation['service_name']) ? $reservation['service_name'] : ''  ?></span></td>
			<td><span class="nobr"><?php echo isset($reservation['date_booking']) ? $reservation['date_booking'] : '' ?></span></td>
			<td><span class="nobr"><?php echo isset($reservation['staff_id']) ? $this->getStaffNameById($reservation['staff_id']) : ''  ?></span></td>
			<td><span class="nobr"><?php echo isset($reservation['time_frame']) ? $reservation['time_frame'] : '' ?></span></td>
			<td><span class="nobr status-column"><?php echo isset($reservation['status']) ? $reservation['status'] : '' ?></span></td>
			<td><span class="nobr"><?php echo isset($reservation['subtotal']) ? Mage::helper('salon')->stringFormatToPrice($reservation['subtotal']) : '' ?></span></td>
			<td>
				<a class="reservation-confirm btn btn-default" href="#">
					<?php echo $this->__("Confirm");?>
				</a>
			</td>
			<td>
				<a class="reservation-delete btn btn-default" href="#">
					<?php echo $this->__("Delete");?>
				</a>
			</td>
		</tr>
        <?php endforeach; ?>
    </tbody>
</table>
<div class="text-center">
	<?php echo $this->getChildHtml('reservation_pager'); ?>
</div>
<script type="text/javascript">
//<![CDATA[
    
    var urlSort = '<?php echo $this->helper('salon')->getUrl('admin/reservation/sort')?>';
   	var sort = '<?php echo $this->getSort(); ?>' ;
   	var page = <?php echo $this->pageNum; ?>;

	jQuery(function($){
		$('.reservation-confirm').on('click',function(){
			var target = $(this).parent().parent();
			var r = confirm("Are you sure?");
			if(r == true)
			{
				$.ajax({
					type: "post",
					url: "<?php echo Mage::helper('salon')->getUrl('admin/reservation/confirm');?>",
					dataType: "json",
					data: {'id': target.attr('title')},
					success: function(response){
						if(response.status == 'SUCCESS')
						{
							target.find('span.status-column').text('complete');
							target.css('background','#f9f9f9');
						}
						else
						{
							alert(response.message);
						}
					}
				});
			}
		});
		$('.reservation-delete').on('click', function(){
			var target = $(this).parent().parent();
			var r = confirm("Are you sure?");
			if(r == true)
			{
				$.ajax({
					type: "post",
					url: "<?php echo Mage::helper('salon')->getUrl('admin/reservation/delete');?>",
					dataType: "json",
					data: {'id': target.attr('title')},
					success: function(response){
						if(response.status == 'SUCCESS')
						{
							target.remove();
						}
						else
						{
							alert(response.message);
						}
					}
				});
			}
		});
	});

	 $(function() {
	    	$('.sort').click( function() {

	    		var cell = $(this).attr('id');

				var iEl = $(this).children('i');

				iEl.removeClass('fa-sort').addClass('fa-refresh fa-spin');

	    		$.getJSON( urlSort, { sortBy : cell, direct:sort , p: page }, function(data) {

					$('tbody.table-content').html(data.data);

					iEl.removeClass('fa-refresh fa-spin').addClass('fa-sort');

					sort = data.direct ;

	    		});
	    	});
	    });
//]]>
</script>


