<div id="classifed-list" class="tabbed-content">
	<ul>
		<li><a href="#">Private Salon Suites for rent. *** FIRST 6 WEEKS FREE!</a></li>
		<li><a href="#">Upscale Salon Suites for Rent - 6 Weeks Free - $50 Cash When You Visit</a></li>
		<li><a href="#">We train, certify, and hire PERSONAL FITNESS TRAINERS</a></li>
		<li><a href="#">Lash Consultant/ Sales Associate</a></li>
		<li><a href="#">Esthetician Wax Associate - Las Colinas</a></li>
		<li><a href="#">Esthetician/Cosmetologist - Allen & Frisco</a></li>
		<li><a href="#">COACH; BJJ purple belt or higher</a></li>
		<li><a href="#">KICKBOXING, BOXING, MMA, BJJ- COACHES</a></li>
		<li><a href="#">Waxing Specialist/Esthetician, Studio Coordinator/Guest Services</a></li>
		<li><a href="#">Rapidly Growing Salon seeks Sensational Front Desk Coordinator</a></li>
	</ul>   
	 <ul class="pagination">
    <li>
      <a href="#" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
      </a>
    </li>
    <li><a href="#">1</a></li>
    <li><a href="#">2</a></li>
    <li><a href="#">3</a></li>
    <li><a href="#">4</a></li>
    <li><a href="#">5</a></li>
    <li>
      <a href="#" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
      </a>
    </li>
  </ul>         
</div>
 
