<script src="https://maps.googleapis.com/maps/api/js?v=3.exp"></script>
<div id="classifed-map" class="tabbed-content">
	<div id="dealer_locator">
		<div id="map_canvas" style="height: 500px"></div>
	</div>
</div>
<script type="text/javascript">
    //<![CDATA[
       var lat = '32.780262';
    var lng = '-96.800978';
    var map;
    function initialize() {
      var mapOptions = {
        zoom: 5,
        center: new google.maps.LatLng(32.780262, -96.800978)
      };
      map = new google.maps.Map(document.getElementById('map_canvas'),
          mapOptions);
    }
    google.maps.event.addDomListener(window, 'load', initialize);
    //]]>
</script>

