<?php $salonArr = $this->getSalon()?>
<div class=" panel panel-default">
	<?php 	$sessionMessageArr = Mage::helper('salon')->getSessionMessage();?>
	<?php if (isset($sessionMessageArr['message']) && $sessionMessageArr['message']):?>
		<div id="message-session" class="<?php echo ($sessionMessageArr['type'] == 'error') ? 'text-danger' : 'text-success'?>">
			<blockquote class="<?php echo ($sessionMessageArr['type'] == 'error') ? 'bg-danger' : 'bg-success'?>">
				<?php echo $sessionMessageArr['message']?>
			</blockquote>
		</div>
	<?php endif;?>
	<div class="panel-heading">
		<?php echo $this->__('User Profile')?>
	</div>
		<form method="post" role="form" id="salon-admin-profile-form" action="<?php echo Mage::helper('salon')->getUrl('admin/profile/save') ?>">
			<div class="form-group">
				<label for="firstname" class="control-label"><em>*</em><?php echo $this->__('First Name') ?></label>
				<input  type="text"  name="firstname" id="firstname"  title="<?php echo $this->__('First Name') ?>" value="<?php echo isset($salonArr['firstname']) ? $salonArr['firstname'] : '' ?>" class="form-control"/>
			</div>
			<div class="form-group">
				<label for="lastname" class="control-label"><?php echo $this->__('Last Name') ?></label>
				<input style="height: 33px;" type="text"  name="lastname" id="lastname"  title="<?php echo $this->__('Last Name') ?>" value="<?php echo isset($salonArr['lastname']) ? $salonArr['lastname'] : '' ?>" class="form-control"/>
			</div>
			<button type="submit" class="btn  btn-lg  btn-save">
				<i class="fa fa-arrow-circle-o-right"></i> <?php echo $this->__('Save')?>
			</button>
		</form>
</div>
