<script type="text/javascript" src="<?php echo $this->getJsUrl() ?>tiny_mce/tiny_mce.js"></script>
<?php $page = $this->getPage();?>
<div class="row">
	<div class="col-sm-10">
		<div class="content-wrapper">
			<?php 	$sessionMessageArr = Mage::helper('salon')->getSessionMessage();?>
			<?php if (isset($sessionMessageArr['message']) && $sessionMessageArr['message']):?>
				<div class="<?php echo ($sessionMessageArr['type'] == 'error') ? 'text-danger' : 'text-success'?>">
					<blockquote class="<?php echo ($sessionMessageArr['type'] == 'error') ? 'bg-danger' : 'bg-success'?>">
						<?php echo $sessionMessageArr['message']?>
					</blockquote>
				</div>
			<?php endif;?>
			<div class="panel-heading">
				<?php if($this->getActionName() == 'edit'):?> 
					 <?php echo $this->__('Edit '). $page->getTitle(). 'page'?> 
				<?php else: ?>
					<?php echo $this->__('New Page')?>
				<?php endif; ?>
			</div>
			<form class="" role="form" action="<?php echo $this->getAction()?>" method="post" id="form-validate" enctype="multipart/form-data">
					<div class="form-group">
						<label for="title-content" class="control-label"><em>*</em><?php echo $this->__('Title') ?></label>
						<input type="text" name="title" id="title-content" title="<?php echo $this->__('Title') ?>" placeholder="<?php echo $this->__('Insert title') ?>"class="form-control required-entry" value="<?php echo $page->getTitle() ? $page->getTitle() : '' ?>" />
					</div>
					<div class="form-group">
						<label for="path" class="control-label"><em>*</em><?php echo $this->__('Content') ?></label>
							<textarea rows="10" id="content" name="content" class="form-control required-entry validate-number" ><?php echo $page->getContent() ? $page->getContent() : '' ?></textarea>
							<script type="text/javascript">
							tinyMCE.init({
						        // General options
						        height: 485,
						        mode : "textareas",
						        theme : "advanced",
						        plugins : "autolink,lists,spellchecker,pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template",
	
						        // Theme options
						        theme_advanced_buttons1 : "save,newdocument,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,|,styleselect,formatselect,fontselect,fontsizeselect",
						        theme_advanced_buttons2 : "cut,copy,paste,pastetext,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,|,insertdate,inserttime,preview,|,forecolor,backcolor",
						        theme_advanced_buttons3 : "tablecontrols,|,hr,removeformat,visualaid,|,sub,sup,|,charmap,emotions,iespell,media,advhr,|,print,|,ltr,rtl,|,fullscreen",
						        theme_advanced_buttons4 : "insertlayer,moveforward,movebackward,absolute,|,styleprops,spellchecker,|,cite,abbr,acronym,del,ins,attribs,|,visualchars,nonbreaking,template,blockquote,pagebreak,|,insertfile,insertimage",
						        theme_advanced_toolbar_location : "top",
						        theme_advanced_toolbar_align : "left",
						        theme_advanced_statusbar_location : "bottom",
						        theme_advanced_resizing : true,
	
						        // Skin options
						        skin : "o2k7",
						        skin_variant : "silver",
	
						        // Example content CSS (should be your site CSS)
						        content_css : "css/example.css",
	
						        // Drop lists for link/image/media/template dialogs
						        template_external_list_url : "js/template_list.js",
						        external_link_list_url : "js/link_list.js",
						        external_image_list_url : "js/image_list.js",
						        media_external_list_url : "js/media_list.js",
	
						        // Replace values for the template plugin
						        template_replace_values : {
						                username : "Some User",
						                staffid : "991234"
						        }
						});
	     					 </script>
					</div>
					<div class="form-group"> 
							<input type="hidden" value="<?php echo $page->getEntityId() ? $page->getEntityId() : '' ?>" name="id"/>
					</div>
					<div class="form-group">
							<button id="submit" type="submit"
								title="<?php echo $this->__('Save') ?>" class="btn btn-default btn-save-information">
								<?php echo $this->__('Save') ?>
							</button>
					</div>
			</form>
		</div>
	</div>
</div>








