<!doctype html>
<html>
  <head>
    <?php echo $this->getChildHtml('head') ?>
  </head>
  <body>
  	<?php echo $this->getChildHtml('header') ?>
  	<div id="main">
	    <div class="container">
	    	<div class="row">
		        <div class="col-md-9 content">
		        	<?php echo $this->getChildHtml('content') ?>
		        </div>
		        <div class="col-md-3 sidebar">
		        	<?php echo $this->getChildHtml('right') ?>
		        </div>
		      </div>
	    </div>
	    <?php echo $this->getChildHtml('footer') ?>
	</div>
	<?php echo $this->getChildHtml('jsfooter') ?>
  </body>
</html>