<?php   $customerData = $this->getCustomerMongo()?>
<div class="">
	<?php 	$sessionMessageArr = Mage::helper('salon')->getSessionMessage();?>
		<?php if (isset($sessionMessageArr['message']) && $sessionMessageArr['message']):?>
		<div class="<?php echo ($sessionMessageArr['type'] == 'error') ? 'text-danger' : 'text-success'?>">
			<blockquote class="<?php echo ($sessionMessageArr['type'] == 'error') ? 'bg-danger' : 'bg-success'?>">
				<?php echo $sessionMessageArr['message']?>
			</blockquote>
		</div>
		<?php endif;?>
	<div class="panel-heading">
			<?php if($this->getActionName() == 'edit'):?> 
				<?php echo $this->__('Edit Customer')?>
			<?php else: ?>
				<?php echo $this->__('New Customer')?>
			<?php endif; ?>
		</div>
	<div class="col-sm-4 col-sm-offset-2 register-wrapper">
		<div class="page-title">
		    <h2><?php echo $this->__('Create A New Customer') ?></h2>
		    <hr/>
		</div>
		<form role="form" action="<?php echo Mage::helper('salon')->getUrl('admin/customer/save') ?>" method="post" id="new-customer-form"  enctype="multipart/form-data" >
		      <input type="hidden" value="<?php echo isset($customerData['entity_id'])  ? $customerData['entity_id'] : '' ?>" name="menuid"/>
		        <ul class="list-unstyled">
	                <li class="form-group">
	                	<label for="firstname" class="control-label"><em>*</em><?php echo $this->__('First Name') ?></label>
		               	<input value="<?php echo isset($customerData['firstname'])  ? $customerData['firstname'] : '' ?>" required data-bv-notempty-message="The first name is required"  type="text" name="firstname" id="firstname" value="<?php echo isset($formData['firstname']) ? $formData['firstname'] : ''?>" class="form-control required-entry" />
	            	</li>
	            	<li class="form-group">
	                	<label for="lastname" class="control-label"><em>*</em><?php echo $this->__('Last Name') ?></label>
	 					<input type="text" name="lastname" id="lastname" value="<?php echo isset($customerData['lastname'])  ? $customerData['lastname'] : '' ?>"  class="form-control required-entry"/>
		            </li>
	            	<li class="form-group">
	                	<label for="email" class="control-label"><em>*</em><?php echo $this->__('Email') ?></label>
 						<input data-bv-emailaddress-message="The value is not a valid email address"  type="email" name="email" id="email" value="<?php echo isset($customerData['email'])  ? $customerData['email'] : '' ?>"  class="form-control required-entry"/>
	            	</li>
	            	<li class="form-group">
	                	<label for="customer_address" class="control-label"><em>*</em><?php echo $this->__('Customer Address') ?></label>
						<input value="<?php echo isset($customerData['address'])  ? $customerData['address'] : '' ?>" type="text" name="address" id="salon_address"  class="form-control required-entry"/>
	            	</li>
	            	<li class="form-group">
	                	<label for="city" class="control-label"><em>*</em><?php echo $this->__('City') ?></label>
						<input value="<?php echo isset($customerData['city'])  ? $customerData['city'] : '' ?>" type="text" name="city" id="city"  class="form-control required-entry"/>
	            	</li>
	            	<li class="form-group">
	                	<label for="region_id" class="control-label"><em>*</em><?php echo $this->__('State/Province') ?></label>
						<select name="region_id" id="region_id" value="" class="form-control required-entry" defaultvalue="0"/>
						<?php $regionCollection = $this->getRegionsByCountryId('US')?>
							<option><?php echo $this->__('Please select region, state or province')?></option>
							<?php foreach ($regionCollection as $region):?>
								<option value="<?php echo $region->getRegionId()?>" 
								<?php 
								 if(isset($customerData) && !empty($customerData))
								 {
									echo ($region->getRegionId() ? $region->getRegionId() : ''  == $customerData['region_id']) ? 'selected="selected"' : '';
								 }
								?>
								><?php echo $region->getName()?></option>
							<?php endforeach;?>
						</select>
	            	</li>
	            	<li class="form-group">
	                	<label for="postcode" class="control-label"><em>*</em><?php echo $this->__('Zip/Postal Code') ?></label>
						<input type="text" value="<?php echo isset($customerData['postcode'])  ? $customerData['postcode'] : '' ?>"  name="postcode" id="postcode" class="form-control required-entry"/>
	            	</li>
	            	<li class="form-group">
	                	<label for="telephone" class="control-label"><em>*</em><?php echo $this->__('Phone Number') ?></label>
						<input type="text" value="<?php echo isset($customerData['telephone'])  ? $customerData['telephone'] : '' ?>"   name="telephone" id="telephone"  class="form-control required-entry"/>
	            	</li>
	            	<button data-action="save-customer-address" type="submit" title="<?php echo $this->__('Create New') ?>" class="button btn btn-primary"><span><span><?php echo $this->__('Save Customer') ?></span></span></button>
		        </ul>
		</form>
	</div>
</div>
</div>
<<script type="text/javascript">
$(document).ready(function() {
    $('#new-customer-form').bootstrapValidator({
        // To use feedback icons, ensure that you use Bootstrap v3.1.0 or later
        feedbackIcons: {
            valid: 'glyphicon glyphicon-ok',
            invalid: 'glyphicon glyphicon-remove',
            validating: 'glyphicon glyphicon-refresh'
        },
        fields: {
        	firstname: {
                validators: {
                    notEmpty: {
                        message: '<?php echo $this->__('FirstName field is required') ?>'
                    },
                   
                }
            },
            lastname: {
                validators: {
                    notEmpty: {
                        message: '<?php echo $this->__('LastName  field is required') ?>'
                    },
                  
                }
            },
            address: {
                validators: {
                    notEmpty: {
                        message: '<?php echo $this->__('Address field is required') ?>'
                    }
                }
            },
            city: {
                validators: {
                    notEmpty: {
                        message: '<?php echo $this->__('City field is required') ?>'
                    }
                    
                }
            },
            email: {
                validators: {
                    notEmpty: {
                        message: '<?php echo $this->__('Email field is required') ?>'
                    }
                 
                }
            },
            postcode: {
                validators: {
                    notEmpty: {
                        message: '<?php echo $this->__('Postcode field is required') ?>'
                    }
                 
                }
            },
            telephone: {
                validators: {
                    notEmpty: {
                        message: '<?php echo $this->__('Telephone field is required') ?>'
                    }
                 
                }
            },
           
        }
    });
});
</script>
