<?php
    $_serviceCollection = $this->getServiceCollection();
    $staffCollection = $this->getStaffCollection();
    $serviceId = $this->getRequest()->getParam('serviceId');
    $staffId = $this->getRequest()->getParam('staffId');
?>
<div class="salon-page row"> 
<div class="col-sm-12">
	<div class="booking-content col-sm-12">
	<div class="col-sm-7">
		<form role="form" class="form-horizontal" action="<?php echo $this->getAction()?>" method="post" enctype="multipart/form-data" id="form-reservation">
			 <div id="parent" class="form-group">
				 <div id="input" class="inline" >
				  	<label for="search_service" class="col-sm-3 control-label"><?php echo $this->__('Select Services:')?> </label>
				   	<div style="padding: 0px" class="dropdown-wrapper col-sm-9">
				   	<select name="search_service" class="form-control selectService selectpicker" id="search_service">
				   		<option value="<?php echo $this->__('all')?>"><?php echo $this->__('All Services')?></option>
			   			<?php foreach ($_serviceCollection as $service):?>
			   				<option value="<?php echo $service->getEntityId()?>" <?php echo ($service->getEntityId() == $serviceId) ? 'selected' : '' ?>> <?php echo $service->getServiceName()?>
			   				</option>
			   			<?php endforeach;?>
				   	</select >
				  	</div>
				 </div>
			 </div>
			 <div id="resultService" style="height: 155px; margin-left:148px; width: 216px; display: none; border: 1px solid #D0D3D4; overflow-y: scroll">
				  <ul id="result_service">
				  </ul>
			 </div>
			<div class="form-group" id="date-reservation">
				<div id="date-wrapper" class="input-box">
					<label for="res-a-date" class="col-sm-3 control-label"><?php echo $this->__('Date Time:')?></label>
					<div class="input-group date col-sm-9" id="res-a-date" data-date-format="dd-mm-yyyy" data-date="<?php echo Mage::helper('salon')->getCurrentDate()?>">
						<input readonly type="text" value="<?php echo $this->_dateSelected ? $this->_dateSelected : Mage::helper('salon')->getCurrentDate()?>" class="form-control"/>
						<span class="input-group-addon add-on">
							<i class="glyphicon glyphicon-calendar icon-calendar"></i>
						</span>
					</div>
				</div>
			</div>
			<div class="form-group">
				<label class="col-sm-3 control-label"><?php echo $this->__('Select Staff')?></label>
				<div class="col-sm-9" style="padding: 0px">
					<select name="staff" class="form-control selectpicker staff-drop-down" id="choose-a-staff">
						<?php foreach($staffCollection as $staff):?>
							<option data-content="<img src='<?php echo $staff->getImgAvatar() ? $staff->getImgAvatar() :  Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB).'skin/'.'frontend/'.'salore/'.'default/'.'images/'.'not-available.jpg' ?>'/>" value="<?php echo $staff->getEntityId() ? $staff->getEntityId() : ''?>" <?php echo ($staff->getEntityId() == $staffId) ? 'selected' : ''?>><?php echo $staff->getName() ? $staff->getName() : ''?></option>
						<?php endforeach;?>
					</select>
				</div>
			</div>	
				<div id="peusedo"></div>
		
			<input type="hidden" id= "hidden-salonkey" name="salonkey" value="<?php echo $this->getSalonKey()?>">
		</form>
	</div>
	<div class="col-sm-5 step-intro">
		<div class="row">
			<ol class="col-sm-offset-2">
				<li><?php echo $this->__('Select a service from the dropdown.')?></li>
				<li><?php echo $this->__('Pick a date.')?></li>
				<li><?php echo $this->__('Choose a time frame.')?></li>
				<li><?php echo $this->__('Click CHECK OUT to order your appointment.')?></li>
			</ol>
		</div>
	</div>
</div>
</div>
<div class="col-sm-12">
	<div id="service-booking-wrapper" class="">
			<?php echo $this->getServicesListHtml()?>	
	</div>
</div>
<script type="text/javascript">
//<![CDATA[
	var prepareData = {
			imgAjxLoading : '<?php echo $this->getSkinUrl('images/res-loading.gif')?>',
			urlFilter : '<?php echo Mage::helper('salon')->getUrl('reservation/ajaxDayCallService')?>',
			urlCheckout: '<?php echo Mage::helper('salon')->getUrl('reservation/checkout')?>',
			serviceWrap : $('#search_service').parent().parent(),
			staffWrap: $('#choose-a-staff').parent().parent(),
			staffInput: $('#choose-a-staff'),
			datepickerWrap : $('#res-a-date'),
			contentWrap: $('#service-booking-wrapper'),
			serviceInput: $('#search_service'),
			btnCheckout: $('#submit-service-checkout'),
	};
	//setup datepicker
    $(function () {
		var datePicker = $('#res-a-date').datepicker().on('changeDate', function(ev){
			datePicker.hide();
			//catch ajax when having change event
			$(prepareData.datepickerWrap).append('<img style="width: 40px; position: absolute; top: 0px; padding-left:10px" alt="ajax loading" src="'+prepareData.imgAjxLoading+'"/>');
			ajaxRenderContent('datechange');
		}).data('datepicker');
	});
	//disble date of past
	var nowTemp = new Date();
    var now = new Date(nowTemp.getFullYear(), nowTemp.getMonth(), nowTemp.getDate(), 0, 0, 0, 0);
    $('#res-a-date').datepicker({
    	onRender: function(date) {
        	return date.valueOf() < now.valueOf() ? 'disabled' : '';
		}
	});
	//catch ajax
	var ajaxRenderContent = function(eventType)
	{
		var parameters = {
			serviceId: $('#search_service').val(),
			dateSelected: $('#res-a-date').children('input').val(),
			staffId: $('#choose-a-staff').val(),
		};
		$.ajax({
    		type: "POST",
    		url: prepareData.urlFilter,
    		data: { serviceId: parameters.serviceId , dateSelected: parameters.dateSelected, staffId: parameters.staffId },
    	    success: function(response){
        	    if(eventType === 'datechange')
        	    {
        	    	$(prepareData.datepickerWrap).children('img').remove();
        	    }
        	    else if((eventType === 'staffchange'))
        	    {
        	    	$(prepareData.staffWrap).children('img').remove();
            	}
        	    else
        	    {
					$(prepareData.serviceWrap).children('img').remove();
             	}
        	    prepareData.contentWrap.html(response);
			}
		});
	}
	
	$(prepareData.serviceInput).change(function(e){
		prepareData.serviceWrap.append('<img style="width: 40px; position: absolute; padding-left:10px" alt="ajax loading" src="'+prepareData.imgAjxLoading+'"/>');
		ajaxRenderContent('servicechange');
	});
	$(prepareData.staffInput).change(function(e){
		prepareData.staffWrap.append('<img style="width: 40px; position: absolute; padding-left:10px" alt="ajax loading" src="'+prepareData.imgAjxLoading+'"/>');
		ajaxRenderContent('staffchange');
	});
	jQuery(function($){
        $('.staff-drop-down ul').attr('style', '');
        $('.staff-drop-down').find('.open').attr('style', '');
	});
//]]>
</script>




