<div class="account-login col-md-4 col-md-offset-2 customer-forgot-password-wrapper">
	<div class="nk-form-wrapper">
		<div class="page-title">
	        <h2><?php echo $this->__('Forgot Your Password?') ?></h2>
	    </div>
	    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
		<form action="<?php echo $this->getUrl('*/*/forgotpasswordpost') ?>" method="post" id="forgotpassword">
		    <div class="fieldset">
		        <h2 class="legend"><?php echo $this->__('Retrieve your password here') ?></h2>
		        <p><?php echo $this->__('Please enter your email address below. You will receive a link to reset your password.') ?></p>
		        
		        <div class="form-group">
		        	<label for="email_address" class="required control-label"><em>*</em><?php echo $this->__('Email Address') ?></label>
					<input type="text" name="email" alt="email" id="email_address" class="form-control required-entry validate-email" value="<?php echo $this->escapeHtml($this->getEmailValue()) ?>" />
		        </div>
		        
		        <?php echo $this->getChildHtml('form.additional.info'); ?>
		        
		    </div>
		    <div class="buttons-set">
		        <p>
		        	<small class="required text-danger pull-right"><?php echo $this->__('* Required Fields') ?></small>
		        	<button type="submit" title="<?php echo $this->__('Submit') ?>" class="btn nk-btn-default"><?php echo $this->__('Submit') ?></button>
		        	<button type="button" class="btn btn-link" onclick="window.location='<?php echo $this->helper('customer')->getLoginUrl() ?>';"><?php echo $this->__('Back to Login') ?></button>
		        </p>
		    </div>
		</form>
	</div>
</div>
<script type= "text/javascript">
//<![CDATA[
	$(document).ready(function() {
	    $('#forgotpassword').bootstrapValidator({
	        // To use feedback icons, ensure that you use Bootstrap v3.1.0 or later
	        feedbackIcons: {
	            valid: 'glyphicon glyphicon-ok',
	            invalid: 'glyphicon glyphicon-remove',
	            validating: 'glyphicon glyphicon-refresh'
	        },
	        fields: {
	        	email: {
	                validators: {
	                    notEmpty: {
	                        message: '<?php echo $this->__('Email is required') ?>'
	                    },
	                    emailAddress: {
	                        message: '<?php echo $this->__('Email is not a valid. Ex: youname@yourdomain.com') ?>'
	                    }
	                }
	            },
	        }
	    });
	});
	//]]>
</script>