<?php $servicecollection = $this->getService()?>
<div class="content-wrapper">
  <div class="panel-heading"><h2><?php echo  $servicecollection->getServiceName() ? $servicecollection->getServiceName() : ''?></h2></div>
	<div class="container">
		<div class="row">
			<div class="col-sm-3">
				<img class="img-responsive" alt="Responsive image" src="<?php echo $servicecollection->getImageService() ? $servicecollection->getImageService() : Mage::getSkinUrl('salore/default/images/not-available.jpg') ?>"/>
			</div>
			<div class="col-sm-6">
				<p><?php echo 'Name : '. $servicecollection->getServiceName() ? $servicecollection->getServiceName() : '' ?></p>
			</div>
			<div class="col-sm-4">
				<p><?php echo  'Duration : ' .$servicecollection->getDuration() ? $servicecollection->getDuration() :''?></p>
			</div>
			<div class="col-sm-6">
				<p><?php echo  'Price : ' . $servicecollection->getPrice() ? $servicecollection->getPrice() :''?></p>
			</div>
			<div class="col-sm-6">
				<p><?php echo  'Description : ' .$servicecollection->getDescription() ? $servicecollection->getDescription() :''?></p>
			</div>
			<div class="col-sm-6">
			 	<p><button type="button" title="<?php echo $this->__('Reservation') ?>" class="btn nk-btn-default btn-cart" onclick="window.location.href = '<?php echo Mage::helper('salon')->getUrl('reservation') .'?serviceId='.$servicecollection->getEntityId()?>'"><span><span><?php echo $this->__('Reservation') ?></span></span></button></p>
			</div>
		</div>
		</div>
	</div>
</div>


