<?php echo $this->getMessagesBlock()->getGroupedHtml()?>
<?php $collection = $this->getServiceCollection()?>
<?php echo $this->getChild('salon_admin_services_header' )->setData('disables' , $this->getDisable())->toHtml()?>
<?php 	$sessionMessageArr = Mage::helper('salon')->getSessionMessage();?>
	<?php if (isset($sessionMessageArr['message']) && $sessionMessageArr['message']):?>
		<div id="message-session" class="<?php echo ($sessionMessageArr['type'] == 'error') ? 'text-danger' : 'text-success'?>">
			<blockquote class="<?php echo ($sessionMessageArr['type'] == 'error') ? 'bg-danger' : 'bg-success'?>">
				<?php echo $sessionMessageArr['message']?>
			</blockquote>
		</div>
	<?php endif;?>
	<div id="message"class="" style="display: none">
		<blockquote class="">
		</blockquote>
	</div>
<div class="page-title">
	<table cellspacing="0" style="width: 100%">
		<tr>
	
			<td style="float: right;">
			</td>
			<td style="float: right; margin-right: 10px; display: none"
				id="btn-delete">
				<p>
					<button type="button"
						title="<?php echo $this->__('Delete Service') ?>"
						class="button btn-cart" id="buttonHidden">
						<span><span><?php echo $this->__('Delete Service') ?></span></span>
					</button>
				</p>
			</td>
		</tr>
	</table>
</div>
<?php //echo $this->getToolbarHtml(); ?>
<?php if($this->checkserviceExist($collection)): ?>
<p> Showing  from <i> <?php echo $this->getFrom(); ?></i>  to  <i><?php echo $this->getTo(); ?> </i>  of  <b><?php echo $this->getTotal();?> </b> Results </p>
<table class="table table-hover table-bordered" id="my-custom-table">
	<thead>
		<tr class="active">
			<th class="center fixed-width-center">
					<div style="float: left; position: relative; top: 4px; margin-left:10px;"	class="simple-checkbox">
						<input class="noborder" type="checkbox" id="selectedall" /> <label for="selectedall">&nbsp</label>
					</div>
			</th>
			<th><?php echo $this->__('Image') ?></th>
			<th>
				<?php echo $this->__('Title') ?>
				<a href="javascript:void(0)" id="service_name" class="sort<?php echo $this->sort === 'service_name' ? ' '. strtolower($this->direct): null; ?>" style="text-decoration:none">&nbsp;<i class="fa fa-sort"></i></a>
			</th>
			<th>
				<?php echo $this->__('Price') ?>
				<a href="javascript:void(0)" id="price" class="sort<?php echo $this->sort === 'price' ? ' '. strtolower($this->direct): null; ?>" style="text-decoration:none">&nbsp;<i class="fa fa-sort"></i></a>
			</th>
			<th><?php echo $this->__('Special Price') ?></th>
			<th>
				<?php echo $this->__('Updated') ?>
				<a href="javascript:void(0)" id="update_at" class="sort<?php echo $this->sort === 'update_at' ? ' '. strtolower($this->direct): null; ?>" style="text-decoration:none">&nbsp;<i class="fa fa-sort"></i></a>
			</th>
			<th>
				<?php echo $this->__('Duration') ?>
				<a href="javascript:void(0)" id="duration" class="sort<?php echo $this->sort === 'duration' ? ' '. strtolower($this->direct): null; ?>" style="text-decoration:none">&nbsp;<i class="fa fa-sort"></i></a>
			</th>
			<th><span class="nobr"><?php echo $this->__('Edit') ?></span></th>
			<th><span class="nobr"><?php echo $this->__('Delete') ?></span></th>
		</tr>
	</thead>
	<tbody class="table-content">
        <?php $_odd = ''; ?>
        <?php foreach ($collection as $service): ?>
        <tr title="<?php echo isset($service['entity_id']) ? $service['entity_id'] : '' ?>">
			<td class="text-center" style="width:50px">
					<div style="line-height:70px; margin-left:10px" class="simple-checkbox">
						<input class="noborder pselect" type="checkbox" onclick="inputSelect(this);"  id ="<?php echo $service['entity_id']; ?>" value="<?php echo $service['entity_id']; ?>" name="productBox[]" />
						<label for="<?php echo $service['entity_id']; ?>">&nbsp</label>   
					</div>
				</td>
			<td>
				<img alt="" src="<?php echo  isset($service['thumbnail_image']['url']) ? $service['thumbnail_image']['url'] : $this->getSkinUrl('images/not-available.jpg');?>" width="75px" height="75px">
			</td>
			<td><span class="nobr"><?php echo isset($service['service_name']) ? $service['service_name'] : ''; ?></span></td>
			<td><span class="nobr"><?php echo isset($service['price']) ? Mage::helper('salon')->stringFormatToPrice($service['price']) : ''; ?></span></td>
			<td><span class="nobr"><?php echo isset($service['special_price']) ? Mage::helper('salon')->stringFormatToPrice($service['special_price']) : ''; ?></span></td>
			<td><span class="nobr"><?php echo isset($service['update_at']) ? date('d-m-Y' , $service['update_at']) : '' ?></span></td>
			<td><span class="nobr"><?php echo isset($service['duration']) ? $service['duration'] : '' ?>'</span></td>
			<td>
				<a class="edit btn btn-default" 
					href="<?php echo $this->helper('salon')->getUrl('admin/service/edit'). "?sid={$service['entity_id']}";?>">
					<?php echo $this->__("Edit");?>
				</a>
			</td>
			<td>
				<a class="service-delete btn btn-default" 
					href="#" onclick="ajaxDelete(this)">
					<?php echo $this->__("Delete");?>
				</a>
			</td>
		</tr>
        <?php endforeach; ?>
    </tbody>
</table>
<div class="text-center">
	<?php echo $this->getChildHtml('service.pager')?>
</div>

<?php else: ?>
<p><?php echo $this->__('The collection is empty.'); ?></p>
<?php endif; ?>
<script type="text/javascript">
//<![CDATA[
    var urlDelete = '<?php echo $this->helper('salon')->getUrl('admin/service/ajaxdelete')?>';
	var urlIndex  = '<?php echo $this->helper('salon')->getUrl('admin/service/index')?>';
	var name = 'service';
	var urlSort = '<?php echo $this->helper('salon')->getUrl('admin/service/sort')?>';
   	var sort = '<?php echo $this->getSort(); ?>' ;
   	var page = <?php echo $this->pageNum; ?>;
	
    function ajaxDelete(arg)
    {
    	$('#message').css("display", "none");
    	if($('#message-session') != null)
    	{
    		$('#message-session').remove();
    	}
    	$('#message').removeClass('animated bounceInDown text-danger text-success'); 
    	$('#message').find('blockquote').removeClass('bg-danger bg-success'); 	
    	var serviceId = $(arg).parent().parent().attr('title');
    	var serviceTitle = $(arg).parent().parent().children().children('span').html();
    	var r = confirm('['+serviceTitle+'] Are you sure want to delete ' + serviceTitle +' service?');
    	if (r == true)
    	  {
    		jQuery.ajax({
        		type: "POST",
        		url: urlDelete,
        		data: { id: serviceId },
        		dataType: "json",
        	    success: function(data){
            	    if(data.status === 'SUCCESS')
            	    {
            	    	$(arg).parent().parent().remove();
            	    	$('#message').addClass('animated bounceInDown text-success').css("display", "block");
    					$('#message').find('blockquote').addClass('bg-success').html(data.message);
                	}
            	    else
            	    {
            	    	$('#message').addClass('animated bounceInDown text-danger').css("display", "block");
    					$('#message').find('blockquote').addClass('bg-danger').html(data.message);        
                	}
    			},
    		}); 
    	  }   	
    }
    
    $(function() {

    	$('.sort').click( function() {

    		var cell = $(this).attr('id');

			var iEl = $(this).children('i');

			iEl.removeClass('fa-sort').addClass('fa-refresh fa-spin');

    		$.getJSON( urlSort, { sortBy : cell, direct:sort , p: page }, function( data) {

				$('tbody.table-content').html( data.data);

				iEl.removeClass('fa-refresh fa-spin').addClass('fa-sort');

				sort = data.direct ;

    		});
    	});
    });
    
//]]>
</script>