<div class="panel-heading">
	<?php echo $this->__('Product Salon')?>
</div>
<div class="action-row">
	<a href="<?php echo $this->helper('salon')->getUrl('admin/product')?>" class="btn btn-default">
		<?php echo Mage::helper('salon')->__('Product List')?>
	</a>
	<a style="margin-left: 9px;" href="<?php echo $this->helper('salon')->getUrl('admin/product/new')?>" class="btn btn-default">
		<?php echo Mage::helper('salon')->__('Add New')?>
	</a>
	<a  <?php echo $this->getDisables(); ?> style="margin-left: 9px;" href="#" class="btn btn-default" id="deleteall">
		<?php echo Mage::helper('salon')->__('Delete selected')?>
	</a>
</div>
