<div class="content-wrapper">
	<?php echo $this->getMessagesBlock()->getGroupedHtml()?>
	<?php $collection = $this->getProductCollectionFromMongo()?>
	<?php echo $this->getChild('salon_admin_product_header' )->setData('disables' , $this->getDisable())->toHtml()?>
	<?php 	$sessionMessageArr = Mage::helper('salon')->getSessionMessage();?>
		<?php if (isset($sessionMessageArr['message']) && $sessionMessageArr['message']):?>
			<div id="message-session" class="<?php echo ($sessionMessageArr['type'] == 'error') ? 'text-danger' : 'text-success'?>">
				<blockquote class="<?php echo ($sessionMessageArr['type'] == 'error') ? 'bg-danger' : 'bg-success'?>">
					<?php echo $sessionMessageArr['message']?>
				</blockquote>
			</div>
		<?php endif;?>
		<div id="message"class="" style="display: none">
			<blockquote class="">
			</blockquote>
		</div>
	
		<div class="page-title">
			<table cellspacing="0" style="width: 100%">
				<tr>
					<td style="float: right;">
					</td>
					<td style="float: right; margin-right: 10px; display: none"
						id="btn-delete">
						<p>
							<button type="button"
								title="<?php echo $this->__('Delete Product') ?>"
								class="button btn-cart" id="buttonHidden">
								<span><span><?php echo $this->__('Delete Product') ?></span></span>
							</button>
						</p>
					</td>
				</tr>
			</table>
		</div>
	<?php if($this->checkProductExist($collection)): ?>
	<p> Showing  from <i> <?php echo $this->getFrom(); ?></i>  to  <i><?php echo $this->getTo(); ?> </i>  of  <b><?php echo $this->getTotal();?> </b> Results </p>
	<div id="product-content">
	<table class="table table-hover table-bordered" id="my-custom-table" >
		<thead>
			<tr class="active">
				<th class="center fixed-width-center">
					<div style="float: left; position: relative; top: 4px; margin-left:10px;"	class="simple-checkbox">
						<input class="noborder" type="checkbox" id="selectedall" /> <label for="selectedall">&nbsp</label>
					</div>
				</th>
				<th><?php echo $this->__('Image') ?></th>
				<th>
					<?php echo $this->__('Title') ?>
					<a href="javascript:void(0)" id="product_name" class="sort<?php echo $this->sort === 'product_name' ? ' '. strtolower($this->direct): null; ?>" style="text-decoration:none">&nbsp;<i <?php if( $this->sort === 'product_name'): ?>style="color:rgb(42,100,150)"<?php endif;?>class="fa fa-sort"></i></a>
				</th>
				<th>
					<?php echo $this->__('Price') ?>
					<a href="javascript:void(0)" id="price" class="sort<?php echo $this->sort === 'price' ? ' '. strtolower($this->direct): null; ?>" style="text-decoration:none">&nbsp;<i class="fa fa-sort"></i></a>
				</th>
				<th>
					<?php echo $this->__('Special Price') ?>
					<a href="javascript:void(0)" style="text-decoration:none">&nbsp;<i class="fa fa-sort"> </i> </a>
				</th>
				<th><span class="nobr"><?php echo $this->__('Edit') ?></span></th>
				<th><span class="nobr"><?php echo $this->__('Delete') ?></span></th>
			</tr>
		</thead>
		<tbody class="table-content">
	        <?php $_odd = ''; ?>
	       <?php foreach ($collection as $product): ?>
	        <tr title="<?php echo isset($product['entity_id']) ? $product['entity_id'] : '' ?>">
				<td class="text-center" style="width:50px">
					<div style="line-height:70px; margin-left:10px" class="simple-checkbox">
						<input class="noborder pselect" type="checkbox" onclick="inputSelect(this);"  id ="<?php echo $product['entity_id']; ?>" value="<?php echo $product['entity_id']; ?>" name="productBox[]" />
						<label for="<?php echo $product['entity_id']; ?>">&nbsp</label>   
					</div>
				</td>
				<td>
					<img alt="" src="<?php echo  isset($product['thumbnail_image']['url']) ? $product['thumbnail_image']['url'] : $this->getSkinUrl('images/not-available.jpg');?>" width="75px" height="75px">
				</td>
		
				<td><span class="nobr"><?php echo isset($product['product_name']) ? $product['product_name'] : ''?></span></td>
				<td><span class="nobr"><?php echo isset($product['price']) ? Mage::helper('salon')->stringFormatToPrice($product['price']) : ''; ?></span></td>
				<td><span class="nobr"><?php echo isset($product['speacial_price']) ? Mage::helper('salon')->stringFormatToPrice($product['speacial_price']) : ''; ?></span></td>
				<td>
					<a class="edit btn btn-default" 
						href="<?php echo $this->helper('salon')->getUrl('admin/product/edit'). "?sid={$product['entity_id']}";?>">
						<?php echo $this->__("Edit");?>
					</a>
				</td>
				<td>
					<a class="product-delete btn btn-default" href="#" onclick="ajaxDelete(this)">
						<?php echo $this->__("Delete");?>
					</a>
				</td>
			</tr>
	        <?php endforeach; ?>
	    </tbody>
	</table>
	</div>
<div class="text-center">
	<?php echo $this->getChildHtml('product.pager')?>
</div>
	<?php else: ?>
	<p><?php echo $this->__('The collection is empty.'); ?></p>
	<?php endif; ?>
</div>
<script type="text/javascript">
//<![CDATA[
    var urlDelete = '<?php echo $this->helper('salon')->getUrl('admin/product/ajaxdelete')?>';
   	var urlIndex  = '<?php echo $this->helper('salon')->getUrl('admin/product/index')?>';
   	var urlSort = '<?php echo $this->helper('salon')->getUrl('admin/product/sort')?>';
   	var name = 'product';
   	var sort = '<?php echo $this->getSort(); ?>' ;
   	var page = <?php echo $this->pageNum; ?>;
    function ajaxDelete(arg) {
    	$('#message').css("display", "none");
    	if($('#message-session') != null)
    	{
    		$('#message-session').remove();
    	}
    	$('#message').removeClass('animated bounceInDown text-danger text-success'); 
    	$('#message').find('blockquote').removeClass('bg-danger bg-success'); 	
    	var serviceId = $(arg).parent().parent().attr('title');
    	var serviceTitle = $(arg).parent().parent().children().children('span').html();
    	var r = confirm('['+serviceTitle+'] Are you sure to delete ' + serviceTitle +' service?');
    	if (r == true)
    	  {
    		jQuery.ajax({
        		type: "POST",
        		url: urlDelete,
        		data: { id: serviceId },
        		dataType: "json",
        	    success: function(data){
            	    if(data.status === 'SUCCESS')
            	    {
            	    	$(arg).parent().parent().remove();
            	    	$('#message').addClass('animated bounceInDown text-success').css("display", "block");
    					$('#message').find('blockquote').addClass('bg-success').html(data.message);
                	}
            	    else
            	    {
            	    	$('#message').addClass('animated bounceInDown text-danger').css("display", "block");
    					$('#message').find('blockquote').addClass('bg-danger').html(data.message);        
                	}
    			},
    		}); 
    	  }   	
    }
    
    $(function() {
    	$('.sort').click( function() {

    		var cell = $(this).attr('id');

			var iEl = $(this).children('i');

			iEl.removeClass('fa-sort').addClass('fa-refresh fa-spin');

    		$.getJSON( urlSort, { sortBy : cell, direct:sort , p: page }, function(data) {

				$('tbody.table-content').html(data.data);

				iEl.removeClass('fa-refresh fa-spin').addClass('fa-sort');

				sort = data.direct ;

    		});
    	});
    });

    
//]]>
</script>
