<div class="footer">
	<div class="container">
		<div class="col-md-2">
			<!-- 
			<h3>
				<a href="http://dev.nailkare.com/" class="logo">
					<img class="large" alt="Nailkare" src="/skin/frontend/nailkare/default/images/nailkare.png">
				</a>
			</h3>
			 -->
		</div>
		<div class="col-md-3">
			<div class="footer-section ">
				<h3 class="footer-header"><?php echo $this->__('Salon owner')?></h3>
				<ul>
					<li>
						<a href="/salon/new" class="footer-link "><?php echo $this->__('Open new salon')?></a>
					</li>
					<li>
						<a href="/salon/login" class="footer-link "><?php echo $this->__('Manage my salon')?></a>
					</li>
					<li>
						<a href="/salon/guide" class="footer-link "><?php echo $this->__('Administration guide')?></a>
					</li>
				</ul>
			</div>
		</div>
		<div class="col-md-3">
			<div class="footer-section "><h3 class="footer-header">Help</h3>
				<ul>
				    <li><a href="/" class="footer-link ">Blog</a></li>
				    <li><a href="/" class="footer-link ">How we work</a></li>
				    <li><a href="/" class="footer-link ">FAQ</a></li>
			    </ul>
			</div>
		</div>
		<div class="col-md-3">
			<div class="footer-section "><h3 class="footer-header">Nailkare</h3>
				<ul>
				    <li><a href="/" class="footer-link ">About</a></li>
				    <li><a href="/" class="footer-link ">Careers</a></li>
				    <li><a href="/" class="footer-link ">Contact</a></li>
				    <li><a href="/" class="footer-link ">Partner program</a></li>
				    <li><a href="/" class="footer-link ">Sitemap</a></li>
			    </ul>
			</div>
		</div>
	</div>
</div>