<?php $salon = $this->getSalon() ?>
<div class="register-wrapper col-sm-4 col-sm-offset-2">
	<div style="border-radius: 4px; border: #ddd 1px solid; padding: 0px 15px">
		<div class="page-title">
		    <h2 class="text-success"><?php echo $this->__('Sorry, the salon %s is pending for review', $salon->getData('salon_name')) ?></h2>
		</div>
		<p class="text-info">
			<?php echo $this->__('Please try again later')?>
		</p>
		<p>
			<?php echo $this->__('Salore team.')?>
		</p>
	</div>
</div>