<?php if($crumbs && is_array($crumbs)): ?>
<div class="row breadcrumbs">
	<div class="col-md-12">
		<ol class="breadcrumb breadcrumb-arrow">
			<?php foreach($crumbs as $_crumbName=>$_crumbInfo): ?>
	            <li class="<?php echo $_crumbName ?> <?php if($_crumbInfo['last']): echo 'active'; endif; ?>">
	            <?php if($_crumbInfo['link']): ?>
	                <a href="<?php echo $_crumbInfo['link'] ?>"
				title="<?php echo $this->escapeHtml($_crumbInfo['title']) ?>"><?php echo $this->escapeHtml($_crumbInfo['label']) ?></a>
	            <?php elseif($_crumbInfo['last']): ?>
	                <span><?php echo $this->escapeHtml($_crumbInfo['label']) ?></span>
	            <?php else: ?>
	                <?php echo $this->escapeHtml($_crumbInfo['label'])?>
	            <?php endif; ?>
	            </li>
	        <?php endforeach; ?>
		</ol>
	</div>
</div>
<?php endif; ?>
