<?php $salon = Mage::registry('currentsalon') ?>
<?php $helper = Mage::helper('salon') ?>
<div class="container">
	<div class="row">
		<div class="col-md-4">
	        <a href="<?php echo $helper->getUrl()?>" class="brand">
	        	<?php if ( $salon->getData('logo') ):?>
	        	<h2 class="logo"><img src="<?php echo $salon->getData('logo')?>" /></h2>
	        	<?php else: ?>
	        	<h2><?php echo $salon->getData('salon_name')?></h2>
	        	<?php endif;?>
		    </a>
		</div>
	  	<div class="col-md-5">
	  		<div class="navbar-search">
	  			<div class="input-group">
		      		<input type="text" class="form-control" />
		      		<span class="input-group-btn">
		        		<button class="btn btn-default" type="button">Search</button>
		      		</span>
		    	</div><!-- /input-group -->
	  		</div>
	  	</div><!-- /.col-lg-6 -->
	  	<div class="col-md-3">
	  		<div class="navbar-hot-line">
	    		HOTLINE: 0925752737
	    	</div>
	  	</div><!-- /.col-lg-6 -->
	</div><!-- /.row -->
</div>
<div role="navigation" class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <button data-target=".navbar-collapse" data-toggle="collapse" class="navbar-toggle" type="button">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div class="navbar-collapse collapse">
          <?php echo $this->getChildHtml('menuLinks') ?>
        </div><!--/.nav-collapse -->
      </div>
    </div>
