<?php echo $this->getMessagesBlock()->getGroupedHtml()?>
<?php $collection = $this->getServiceCollection()?>
<?php echo $this->getChildHtml('salon_admin_services_header')?>
<?php 	$sessionMessageArr = Mage::helper('salon')->getSessionMessage();?>
	<?php if (isset($sessionMessageArr['message']) && $sessionMessageArr['message']):?>
		<div id="message-session" class="<?php echo ($sessionMessageArr['type'] == 'error') ? 'text-danger' : 'text-success'?>">
			<blockquote class="<?php echo ($sessionMessageArr['type'] == 'error') ? 'bg-danger' : 'bg-success'?>">
				<?php echo $sessionMessageArr['message']?>
			</blockquote>
		</div>
	<?php endif;?>
	<div id="message"class="" style="display: none">
		<blockquote class="">
		</blockquote>
	</div>
<div class="page-title">
	<table cellspacing="0" style="width: 100%">
		<tr>
	
			<td style="float: right;">
			</td>
			<td style="float: right; margin-right: 10px; display: none"
				id="btn-delete">
				<p>
					<button type="button"
						title="<?php echo $this->__('Delete Service') ?>"
						class="button btn-cart" id="buttonHidden">
						<span><span><?php echo $this->__('Delete Service') ?></span></span>
					</button>
				</p>
			</td>
		</tr>
	</table>
</div>
<?php //echo $this->getToolbarHtml(); ?>
<?php if($this->checkserviceExist($collection)): ?>
<table class="table table-hover" id="my-custom-table">
	<thead>
		<tr class="active">
			<th><?php echo $this->__('Image') ?></th>
			<th><?php echo $this->__('Title') ?></th>
			<th><?php echo $this->__('Price') ?></th>
			<th><?php echo $this->__('Special Price') ?></th>
			<th><?php echo $this->__('Duration') ?></th>
			<th><span class="nobr"><?php echo $this->__('Edit') ?></span></th>
			<th><span class="nobr"><?php echo $this->__('Delete') ?></span></th>
		</tr>
	</thead>
	<tbody>
        <?php $_odd = ''; ?>
        <?php foreach ($collection as $service): ?>
        <tr title="<?php echo isset($service['entity_id']) ? $service['entity_id'] : '' ?>">
			<td>
				<img alt="" src="<?php echo  isset($service['image_service']) ? $service['image_service'] : $this->getSkinUrl('images/not-available.jpg');?>" width="75px" height="75px">
			</td>
			<td><span class="nobr"><?php echo isset($service['service_name']) ? $service['service_name'] : ''; ?></span></td>
			<td><span class="nobr"><?php echo isset($service['price']) ? Mage::helper('salon')->stringFormatToPrice($service['price']) : ''; ?></span></td>
			<td><span class="nobr"><?php echo isset($service['speacial_price']) ? Mage::helper('salon')->stringFormatToPrice($service['speacial_price']) : ''; ?></span></td>
			<td><span class="nobr"><?php echo isset($service['duration']) ? $service['duration'] : '' ?>'</span></td>
			<td>
				<a class="edit" 
					href="<?php echo $this->helper('salon')->getUrl('admin/service/edit'). "?sid={$service['entity_id']}";?>">
					<?php echo $this->__("Edit");?>
				</a>
			</td>
			<td>
				<a class="service-delete" 
					href="#" onclick="ajaxDelete(this)">
					<?php echo $this->__("Delete");?>
				</a>
			</td>
		</tr>
        <?php endforeach; ?>
    </tbody>
</table>
<div class="text-center">
	<?php echo $this->getChildHtml('service.pager')?>
</div>

<?php else: ?>
<p><?php echo $this->__('The collection is empty.'); ?></p>
<?php endif; ?>
<script type="text/javascript">
//<![CDATA[
    var urlDelete = '<?php echo $this->helper('salon')->getUrl('admin/service/ajaxdelete')?>';
   
    function ajaxDelete(arg)
    {
    	$('#message').css("display", "none");
    	if($('#message-session') != null)
    	{
    		$('#message-session').remove();
    	}
    	$('#message').removeClass('animated bounceInDown text-danger text-success'); 
    	$('#message').find('blockquote').removeClass('bg-danger bg-success'); 	
    	var serviceId = $(arg).parent().parent().attr('title');
    	var serviceTitle = $(arg).parent().parent().children().children('span').html();
    	var r = confirm('['+serviceTitle+'] Are you sure want to delete ' + serviceTitle +' service?');
    	if (r == true)
    	  {
    		jQuery.ajax({
        		type: "POST",
        		url: urlDelete,
        		data: { id: serviceId },
        		dataType: "json",
        	    success: function(data){
            	    if(data.status === 'SUCCESS')
            	    {
            	    	$(arg).parent().parent().remove();
            	    	$('#message').addClass('animated bounceInDown text-success').css("display", "block");
    					$('#message').find('blockquote').addClass('bg-success').html(data.message);
                	}
            	    else
            	    {
            	    	$('#message').addClass('animated bounceInDown text-danger').css("display", "block");
    					$('#message').find('blockquote').addClass('bg-danger').html(data.message);        
                	}
    			},
    		}); 
    	  }   	
    }
//]]>
</script>
