<!-- /.row -->
<?php $customerCollection = $this->getCustomerCollection() ?>
<div class="row">
	<div class="col-lg-12">
	<?php 	$sessionMessageArr = Mage::helper('salon')->getSessionMessage();?>
		<div class="menu-wrapper">
			<div class="panel-heading">
				<?php echo $this->__('Salon Customer')?>
			</div>
			<div class="action-row">
				<a href="<?php echo $this->helper('salon')->getUrl('admin/customer/new')?>" class="btn btn-default"><?php echo $this->__('Add New')?></a>
			</div>
			<?php if (isset($sessionMessageArr['message']) && $sessionMessageArr['message']):?>
			<div id="message-session"class="<?php echo ($sessionMessageArr['type'] == 'error') ? 'text-danger' : 'text-success'?>">
				<blockquote class="<?php echo ($sessionMessageArr['type'] == 'error') ? 'bg-danger' : 'bg-success'?>" >
					<?php echo $sessionMessageArr['message']?>
				</blockquote>
			</div>
	<?php endif;?>
			<div id="message"class="" style="display: none">
				<blockquote class="">
				</blockquote>
			</div>
			<div class="panel-body" style="padding: 0px">
				<div class="row">
					<div class="col-lg-12">
						<table id="dataTables-menu" class="table no-footer">
							<thead>
								<tr role="row">
									<th><?php echo $this->__('First Name')?></th>
									<th><?php echo $this->__('Last Name')?></th>
									<th><?php echo $this->__('Email')?></th>
									<th><?php echo $this->__('Telephone')?></th>
									<th><?php echo $this->__('Address')?></th>
									<th><?php echo $this->__('City')?></th>
									<th><?php echo $this->__('Edit')?></th>
									<th><?php echo $this->__('Delete')?></th>
								</tr>
							</thead>
							<tbody>
								<?php $index = 0 ?>
								<?php foreach ($customerCollection as $customerItem):?>
								<tr title="<?php echo $customerItem->getEntityId()?>" class="gradeA <?php if (($index%2) == 0):?>old<?php else: ?>even<?php endif;?>">
									<td class=" "><?php echo $customerItem->getFirstname()?></td>
										<td class=" "><?php echo $customerItem->getLastname()?></td>
											<td class=" "><?php echo $customerItem->getEmail()?></td>
												<td class=" "><?php echo $customerItem->getTelephone()?></td>
													<td class=" "><?php echo $customerItem->getAddress()?></td>
														<td class=" "><?php echo $customerItem->getCity()?></td>
									<td><a style="color: #c79800" href="<?php echo Mage::helper('salon')->getUrl('admin/customer/edit') . '?id=' . $customerItem->getData('entity_id') ?>">Edit</a></td>
									<td><a onclick="ajaxDelete(this)"  style="color: #c79800" href="#">Delete</a></td>
								</tr>
								<?php $index++ ?>
								<?php endforeach;?>
							</tbody>
						</table>
					</div>
				</div>
				<!-- /.row (nested) -->
			</div>
			<!-- /.panel-body -->
		</div>
		<!-- /.panel -->
	</div>
	<!-- /.col-lg-12 -->
</div>
<!-- /.row -->

<script type="text/javascript">
//<![CDATA[


var urlDelete = '<?php echo $this->helper('salon')->getUrl('admin/customer/ajaxdelete')?>';
function ajaxDelete(arg)
{
	$('#message').css("display", "none");
	if($('#message-session') != null)
	{
		$('#message-session').remove();
	}
	$('#message').removeClass('animated bounceInDown text-danger text-success'); 
	$('#message').find('blockquote').removeClass('bg-danger bg-success'); 	
	var menuId = $(arg).parent().parent().attr('title');
	var r = confirm(' Are you sure delete customer ');
	if (r == true)
	  {
		jQuery.ajax({
    		type: "POST",
    		url: urlDelete,
    		data: { id: menuId },
    		dataType: "json",
    	    success: function(data){
        	    if(data.status === 'SUCCESS')
        	    {
        	    	 $('#message').addClass('animated bounceInDown text-success').css("display", "block");
 					$('#message').find('blockquote').addClass('bg-success').html(data.message);    
        	    	$(arg).parent().parent().remove();
            	}
        	    else
        	    {
        	    	 $('#message').addClass('animated bounceInDown text-danger').css("display", "block");
  					$('#message').find('blockquote').addClass('bg-danger').html(data.message); 
            	}
			},
		}); 
	  }   	
}
 
//]]>
</script>

						


