<!-- /.row -->
<?php $menuCollection = $this->getMenuCollection() ?>
<div class="row">
	<div class="col-lg-12">
	<?php 	$sessionMessageArr = Mage::helper('salon')->getSessionMessage();?>
		<div class="menu-wrapper">
			<div class="panel-heading">
				<?php echo $this->__('Salon menu')?>
			</div>
			<div class="action-row">
				<a href="<?php echo $this->helper('salon')->getUrl('admin/menu/new')?>" class="btn btn-default"><?php echo $this->__('Add New')?></a>
			</div>
			<?php if (isset($sessionMessageArr['message']) && $sessionMessageArr['message']):?>
			<div id="message-session"class="<?php echo ($sessionMessageArr['type'] == 'error') ? 'text-danger' : 'text-success'?>">
				<blockquote class="<?php echo ($sessionMessageArr['type'] == 'error') ? 'bg-danger' : 'bg-success'?>" >
					<?php echo $sessionMessageArr['message']?>
				</blockquote>
			</div>
	<?php endif;?>
			<div id="message"class="" style="display: none">
				<blockquote class="">
				</blockquote>
			</div>
			<div class="panel-body" style="padding: 0px">
				<div class="row">
					<div class="col-lg-12">
						<table id="dataTables-menu" class="table no-footer table-bordered">
							<thead>
								<tr role="row">
									<th><?php echo $this->__('Title')?></th>
									<th><?php echo $this->__('Position')?></th>
									<th><?php echo $this->__('Path')?></th>
									<th><?php echo $this->__('Action')?></th>
									<th><?php echo $this->__('Edit')?></th>
									<th><?php echo $this->__('Delete')?></th>
								</tr>
							</thead>
							<tbody>
								<?php $index = 0 ?>
								<?php foreach ($menuCollection as $menuItem):?>
								<tr title="<?php echo $menuItem->getData('entity_id')?>" class="gradeA <?php if (($index%2) == 0):?>old<?php else: ?>even<?php endif;?>">
									<td class="sorting_1"><?php echo $menuItem->getData('title')?></td>
									<td class=" "><input type="text" name="position" id="position" onblur="updatepostion(this)" value="<?php echo $menuItem->getData('position')?>"></td>
									<td class=" "><?php echo $menuItem->getData('path')?></td>
									<td class=" ">
										<div class="btn-group btn-toggle"> 
									    	<button class="btn btn-sm btn-default power <?php echo ((int)$menuItem->getData('active') == 1 ) ? 'active btn-primary' : ''?>">ON</button>
									    	<button class="btn btn-sm btn-default power <?php echo ((int)$menuItem->getData('active') == 0) ? 'active btn-primary' : ''?>">OFF</button>
									  	</div>
									</td>
									<td><a class="btn btn-default" href="<?php echo Mage::helper('salon')->getUrl('admin/menu/edit') . '?id=' . $menuItem->getData('entity_id') ?>">Edit</a></td>
									<td><a onclick="ajaxDelete(this)"  class="btn btn-default" href="javascript:avoid(0)">Delete</a></td>
								</tr>
								<?php $index++ ?>
								<?php endforeach;?>
							</tbody>
						</table>
					</div>
				</div>
				<!-- /.row (nested) -->
			</div>
			<!-- /.panel-body -->
		</div>
		<!-- /.panel -->
	</div>
	<!-- /.col-lg-12 -->
</div>
<!-- /.row -->

<script type="text/javascript">
//<![CDATA[
$('.power').click(function(event){
	$('#message').css("display", "none");
	if($('#message-session') != null)
	{
		$('#message-session').remove();
	}
	$('#message').removeClass('animated bounceInDown text-danger text-success'); 
	$('#message').find('blockquote').removeClass('bg-danger bg-success'); 	
	var button = this;
	var menuId = $(this).parent().parent().parent().attr('title');
	var active = $(this).html();
	var urlActive = '<?php echo $this->helper('salon')->getUrl('admin/menu/ajaxactive')?>';
	var str = $(this).attr('class');
	var classArr = str.split(" ");
	var checkActive = null;
	classArr.forEach(function(item){
		if(item === 'active')
		{
			checkActive = item;
		}
	});
	if(checkActive == null)
	{
		///ajax is here
		jQuery.ajax({
    		type: "POST",
    		url: urlActive,
    		data: { id: menuId , active : active },
    		dataType: "json",
    	    success: function(data){
        	    if(data.status === 'SUCCESS')
        	    {
            	    $(button).addClass('active btn-primary');
					if(active === 'ON')
					{
						$(button).next().removeClass('active btn-primary');
					}
					else
					{
						$(button).prev().removeClass('active btn-primary');
					}   
					$('#message').addClass('animated bounceInDown text-success').css("display", "block");
					$('#message').find('blockquote').addClass('bg-success').html(data.message);
            	}
        	    else
        	    {
        	    	$('#message').addClass('animated bounceInDown text-danger').css("display", "block");
					$('#message').find('blockquote').addClass('bg-danger').html(data.message);            	     
            	}
			},
		}); 
	}
	else
	{
		return false;
	}
}); 

var urlDelete = '<?php echo $this->helper('salon')->getUrl('admin/menu/ajaxdelete')?>';
function ajaxDelete(arg)
{
	$('#message').css("display", "none");
	if($('#message-session') != null)
	{
		$('#message-session').remove();
	}
	$('#message').removeClass('animated bounceInDown text-danger text-success'); 
	$('#message').find('blockquote').removeClass('bg-danger bg-success'); 	
	var menuId = $(arg).parent().parent().attr('title');
	var menuTitle = $(arg).parent().parent().children().first().html();
	var r = confirm('['+menuTitle+'] Are you sure remove ' + menuTitle + ' menu?');
	if (r == true)
	  {
		jQuery.ajax({
    		type: "POST",
    		url: urlDelete,
    		data: { id: menuId },
    		dataType: "json",
    	    success: function(data){
        	    if(data.status === 'SUCCESS')
        	    {
        	    	 $('#message').addClass('animated bounceInDown text-success').css("display", "block");
 					$('#message').find('blockquote').addClass('bg-success').html(data.message);    
        	    	$(arg).parent().parent().remove();
            	}
        	    else
        	    {
        	    	 $('#message').addClass('animated bounceInDown text-danger').css("display", "block");
  					$('#message').find('blockquote').addClass('bg-danger').html(data.message); 
            	}
			},
		}); 
	  }   	
}
function updatepostion(arg)
{
	var urlSave = '<?php echo Mage::helper('salon')->getUrl('admin/menu/updatePosition') ?>';
    var menuId = $(arg).parent().parent().attr('title');
    
    var positionValue = $(arg).val();
    jQuery.ajax({
		type: "POST",
		url: urlSave,
		data: { id: menuId , value: positionValue },
		dataType: "json",
	    success: function(data){
   	    if(data.status === 'SUCCESS')
   	    {
   	    	
       	}
		},
	}); 
}
/* $("#position").blur(function(){
		
	    	
 }); */
 
//]]>
</script>

						


