<?php $menu = $this->getMenu();?>
<div class="row">
	<div class="col-sm-12">
		<?php 	$sessionMessageArr = Mage::helper('salon')->getSessionMessage();?>
		<?php if (isset($sessionMessageArr['message']) && $sessionMessageArr['message']):?>
		<div class="<?php echo ($sessionMessageArr['type'] == 'error') ? 'text-danger' : 'text-success'?>">
			<blockquote class="<?php echo ($sessionMessageArr['type'] == 'error') ? 'bg-danger' : 'bg-success'?>">
				<?php echo $sessionMessageArr['message']?>
			</blockquote>
		</div>
		<?php endif;?>
		
		<div class="panel-heading">
			<?php if($this->getActionName() == 'edit'):?> 
				<?php echo $this->__('Edit menu')?>
			<?php else: ?>
				<?php echo $this->__('New menu')?>
			<?php endif; ?>
		</div>
		<div class="col-sm-6 menu-wrapper">
			<form class="form-horizontal" role="form" action="<?php echo $this->getAction()?>" method="post" id="form-validate" enctype="multipart/form-data">
				<input type="hidden" value="<?php echo $menu->getEntityId() ? $menu->getEntityId() : '' ?>" name="menuid"/>
				<div class="form-group">
					<label for="title-content"><?php echo $this->__('Title') ?><em>*</em></label>
					<input type="text" name="title" id="title-content" title="<?php echo $this->__('Title') ?>" placeholder="<?php echo $this->__('Insert title') ?>"class="form-control required-entry" value="<?php echo $menu->getTitle() ? $menu->getTitle() : '' ?>" required/>
				</div>
				<div class="form-group">
					<label for="title-content"><?php echo $this->__('Position') ?><em>*</em></label>
					 <input type="number" name="position" id="position" title="<?php echo $this->__('Position') ?>" placeholder="<?php echo $this->__('Insert position') ?>"class="form-control required-entry" min="0" max="1000" step="1" value="<?php echo $menu->getPosition() ?>">
				</div>
				<div class="form-group">
					<label for="link"><?php echo $this->__('Link') ?><em>*</em></label>
					<select id="link" name="link" class="form-control">
							<?php foreach (Mage::helper('salon')->getLinksForOption() as $link  => $page):?>
								<option value="<?php echo $link?>"><?php echo $page?></option>
							<?php endforeach;?>					
					</select>
				</div>
				<div class="form-group">
					<label for="menu-active"><?php echo $this->__('Active') ?><em>*</em></label>
					<select id="menu-active" name="active" class="required-entry validate-number form-control"/>
						<?php for($i = 0; $i < 2; $i++):?>
							<option value="<?php echo $i?>" <?php echo ($menu->getActive() == $i) ? 'selected="selected"' : ''?>><?php echo (0 == $i) ? 'No' : 'Yes'?></option>
						<?php endfor;?>
					</select>
				</div>
				<div class="form-group">
					<button id="submit" type="submit"
						title="<?php echo $this->__('Save Menu') ?>" class="btn btn-default btn-save-information">
						<?php echo $this->__('Save Menu') ?>
					</button>
				</div>
			</form>
		</div>
	</div>
</div>







