<?php $salon = $this->getSalon() ?>
<div class="register-wrapper col-sm-4 col-sm-offset-2">
	<div style="border-radius: 4px; border: #ddd 1px solid; padding: 0px 15px">
		<div class="page-title">
		    <h2 class="text-success"><?php echo $this->__('Register new salon successfully!') ?></h2>
		</div>
		<p class="text-info">
			<?php echo $this->__('Hello ')?><?php echo $salon->getData('firstname') ?> <?php echo $salon->getData('lastname') ?>
		</p>
		<p class="text-info">
			<?php echo $this->__('Thank you for register new salon with us')?>
		</p>
		<p class="text-info">
			<?php echo $this->__('We have sent a comfirmation email to %s', $salon->getData('email'))?>
		</p>
		<p class="text-info">
			<?php echo $this->__('We are going to review your salon information. If all your information correct, your salon will be active in 1 hour.')?>
		</p>
		<p>
			<?php echo $this->__('Salore team.')?>
		</p>
	</div>
</div>