<?php $domain = $this->getDomain();?>
<div class="settings-wapper">
		<div class="panel-heading"><?php echo $this->__('Domain setting')?></div>
		<?php 	$sessionMessageArr = Mage::helper('salon')->getSessionMessage();?>
	<?php if (isset($sessionMessageArr['message']) && $sessionMessageArr['message']):?>
		<div class="<?php echo ($sessionMessageArr['type'] == 'error') ? 'text-danger' : 'text-success'?>">
			<blockquote class="<?php echo ($sessionMessageArr['type'] == 'error') ? 'bg-danger' : 'bg-success'?>">
				<?php echo $sessionMessageArr['message']?>
			</blockquote>
		</div>
	<?php endif;?>
	<div class="form-wrapper">
		<form role="form" action="<?php echo Mage::helper('salon')->getUrl('admin/domain/save')?>" method="post" id="form-setting"  enctype="multipart/form-data" class="form-horizontal col-sm-12">
			<div class="form-group">
			    <label for="domain-name"><?php echo $this->__('Domain Name')?></label>
			    <input type="text" class="form-control" id="domain-name" name="domain" value="<?php echo $domain?>">
		 	</div>
		 	<div class="form-group">
		 		<p class="description"><small><i><?php echo $this->__('Your domain name must be in format: domain.xyz. Example: salore.com')?></i></small></p>
		 	</div>
		 	<div class="form-group">
		 	 	<button type="submit" class="btn btn-default"><?php echo $this->__('Save')?></button>
		 	 </div>
		</form>
	</div>
</div>
